=== S0c5/qtopology/src/topology_config_schema.json
{
    "id": "https://github.com/bergloman/NodeProcessManager:topology",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "general": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "coordination_port": {
                    "type": "integer"
                },
                "heartbeat": {
                    "type": "integer"
                },
                "initialization": {
                    "type": "object",
                    "properties": {
                        "working_dir": {
                            "type": "string"
                        },
                        "cmd": {
                            "type": "string"
                        },
                        "init": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "required": [
                        "working_dir",
                        "cmd"
                    ]
                },
                "shutdown": {
                    "type": "object",
                    "properties": {
                        "working_dir": {
                            "type": "string"
                        },
                        "cmd": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "working_dir",
                        "cmd"
                    ]
                }
            },
            "required": [
                "name",
                "coordination_port",
                "heartbeat"
            ]
        },
        "workers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "name"
                ]
            }
        },
        "spouts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "worker": {
                        "type": "string"
                    },
                    "type": {
                        "enum": [
                            "subproc",
                            "inproc",
                            "sys"
                        ],
                        "default": "subproc"
                    },
                    "disabled": {
                        "type": "boolean",
                        "default": true
                    },
                    "working_dir": {
                        "type": "string"
                    },
                    "cmd": {
                        "type": "string"
                    },
                    "init": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "required": [
                    "name",
                    "worker",
                    "working_dir",
                    "cmd",
                    "init"
                ]
            }
        },
        "bolts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "worker": {
                        "type": "string"
                    },
                    "type": {
                        "enum": [
                            "subproc",
                            "inproc",
                            "sys"
                        ]
                    },
                    "disabled": {
                        "type": "boolean",
                        "default": true
                    },
                    "working_dir": {
                        "type": "string"
                    },
                    "cmd": {
                        "type": "string"
                    },
                    "inputs": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "source": {
                                    "type": "string"
                                },
                                "stream_id": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "source"
                            ]
                        }
                    },
                    "init": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "required": [
                    "name",
                    "worker",
                    "working_dir",
                    "cmd",
                    "inputs",
                    "init"
                ]
            }
        },
        "variables": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "string"
                }
            }
        }
    },
    "required": [
        "general",
        "workers",
        "spouts",
        "bolts",
        "variables"
    ]
}

=== S0c5/qtopology/demo/local/topology.json
{
    "general": {
        "name": "Topology name",
        "coordination_port": 9289,
        "heartbeat": 3200
    },
    "workers": [
        {
            "name": "srv1"
        }
    ],
    "spouts": [
        {
            "name": "pump1",
            "worker": "srv1",
            "type": "inproc",
            "working_dir": ".",
            "cmd": "spout_inproc.js",
            "args": [
                "-a",
                "action1"
            ],
            "init": {}
        }
    ],
    "bolts": [
        {
            "name": "bolt3",
            "worker": "srv1",
            "working_dir": ".",
            "type": "inproc",
            "cmd": "bolt_inproc.js",
            "args": [],
            "inputs": [
                {
                    "source": "pump1"
                }
            ],
            "init": {
                "forward": false
            }
        }
    ],
    "variables": {}
}

=== S0c5/qtopology/demo/std_nodes/rest/topology.json
{
    "general": {
        "name": "Demo of POST and REST nodes",
        "coordination_port": 9289,
        "heartbeat": 1000
    },
    "workers": [
        {
            "name": "srv1"
        }
    ],
    "spouts": [
        {
            "name": "pump_timer",
            "worker": "srv1",
            "type": "sys",
            "working_dir": "",
            "cmd": "timer",
            "init": {
                "extra_fields": {
                    "field1": "a"
                }
            }
        },
        {
            "name": "pump_rest",
            "worker": "srv1",
            "type": "sys",
            "working_dir": "",
            "cmd": "rest",
            "init": {
                "port": 6789
            }
        }
    ],
    "bolts": [
        {
            "name": "bolt1",
            "worker": "srv1",
            "working_dir": ".",
            "type": "sys",
            "cmd": "post",
            "inputs": [
                {
                    "source": "pump_timer"
                }
            ],
            "init": {
                "url": "http://localhost:6789"
            }
        },
        {
            "name": "bolt2",
            "worker": "srv1",
            "working_dir": ".",
            "type": "sys",
            "cmd": "console",
            "inputs": [
                {
                    "source": "pump_rest"
                }
            ],
            "init": {}
        }
    ],
    "variables": {}
}

=== S0c5/qtopology/demo/qminer/topology.json
{
    "general": {
        "name": "QMiner demo",
        "coordination_port": 9289,
        "heartbeat": 2000
    },
    "workers": [
        {
            "name": "srv1"
        }
    ],
    "spouts": [
        {
            "name": "pump1",
            "worker": "srv1",
            "type": "inproc",
            "working_dir": ".",
            "cmd": "spout_1.js",
            "args": [],
            "init": {}
        }
    ],
    "bolts": [
        {
            "name": "bolt_qm",
            "worker": "srv1",
            "working_dir": ".",
            "type": "inproc",
            "cmd": "bolt_qm.js",
            "args": [],
            "inputs": [
                {
                    "source": "pump1"
                }
            ],
            "init": {}
        }
    ],
    "variables": {}
}

=== S0c5/qtopology/demo/local/topology_demo.json
{
    "general": {
        "name": "Topology name",
        "coordination_port": 9289,
        "heartbeat": 3200
    },
    "workers": [
        {
            "name": "srv1"
        }
    ],
    "spouts": [
        {
            "name": "pump1",
            "worker": "srv1",
            "type": "inproc",
            "working_dir": ".",
            "cmd": "spout_inproc.js",
            "init": {}
        },
        {
            "name": "pump2",
            "worker": "srv1",
            "type": "inproc",
            "working_dir": ".",
            "cmd": "spout_inproc.js",
            "init": {}
        }
    ],
    "bolts": [
        {
            "name": "bolt1",
            "worker": "srv1",
            "working_dir": ".",
            "type": "inproc",
            "cmd": "bolt_inproc.js",
            "inputs": [
                {
                    "source": "pump1"
                }
            ],
            "init": {}
        },
        {
            "name": "bolt2",
            "worker": "srv1",
            "working_dir": ".",
            "type": "subproc",
            "cmd": "bolt_subproc.js",
            "inputs": [
                {
                    "source": "pump1"
                },
                {
                    "source": "pump2"
                }
            ],
            "init": {
                "forward": true
            }
        },
        {
            "name": "bolt3",
            "worker": "srv1",
            "working_dir": ".",
            "type": "inproc",
            "cmd": "bolt_inproc.js",
            "inputs": [
                {
                    "source": "bolt2"
                }
            ],
            "init": {
                "forward": false
            }
        }
    ],
    "variables": {}
}
